name: Deploy to Cloud

on:
  push:
    branches: [ "main" ]  # Активируется при пуше в main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Шаг 1: Получить код ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Шаг 2: Сборка Docker-образов ---
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker tag myapp-api-gateway myusername/api-gateway:latest
          docker tag myapp-auth-service myusername/auth-service:latest

      # --- Шаг 3: Логин в Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Шаг 4: Пуш образов в Docker Hub ---
      - name: Push images to Docker Hub
        run: |
          docker push myusername/api-gateway:latest
          docker push myusername/auth-service:latest

      # --- Шаг 5: Деплой на сервер ---
      - name: Deploy to Oracle Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/myapp
            docker-compose down
            docker-compose pull
            docker-compose -f docker-compose.prod.yml up -d
